version: "3.2"
services:
  SmartMenu:
    build: ./app
    container_name: SmartMenu
    ports:
      - "8000:8000"
    restart: on-failure
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]